### ISSUE TITLE
This only works on your computer!

### ISSUE THREAD

**Issue by callumacrae** [dareko/ansible-oracle-client#1]
https://github.com/dareko/ansible-oracle-client/blob/master/tasks/main.yml#L5

You're doing it wrong :smile:

**Comment by aguynamedryan** [comment]
I've addressed this, and other things, in #2

**Comment by dareko** [comment]
@aguynamedryan, thank you for the updates. I've merged them and they are now published on galaxy.ansible.com.

@callumacrae, the issue is fixed now.
